---
- import_tasks: detect.yml

- import_tasks: version.yml
  when: kubernetes.installed

- import_tasks: node_role.yml
  when: kubernetes.installed

- import_tasks: components.yml
  when:
    - kubernetes.installed
    - "'control-plane' in kubernetes.node_roles"

- import_tasks: report.yml
  when:
    - kubernetes.installed